# version: '3.8'

# services:
#   mysql:
#     image: mysql:8.0  # Use the version you need
#     container_name: mysql_container
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: admin # Change this to a secure password
#       MYSQL_DATABASE: ferp_go
#       MYSQL_USER: admin
#       MYSQL_PASSWORD: admin  # Change this to a secure password
#     ports:
#       - "3307:3306"
#     volumes:
#       - mysql_data:/var/lib/mysql
#     networks:
#       - my_network

# volumes:
#   mysql_data:

# networks:
#   my_network:
version: '3.8'

services:

  db:
    image: postgres:16.3
    container_name: ferpgo
    environment:
      POSTGRES_DB: ferpgo
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

    volumes:
      - db-data:/var/lib/postgresql/data
    
    ports:
      - "5433:5432"
volumes:
  db-data: